--author::AngryCarrot789
mon = peripheral.wrap("top")
term.setBackgroundColor(colors.pink)
mon.setTextScale(4)
mon.setCursorPos(5,2)
mon.write("OI YOU!")
mon.setCursorPos(3,4)
mon.write("GET OUT ME")
mon.setCursorPos(3,5)
mon.write("FOOKIN HEAD!")